chromoid_web/lib/chromoid_web/router.ex
defmodule ChromoidWeb.Router do
  use ChromoidWeb, :router

  import ChromoidWeb.UserAuth
  import Phoenix.LiveDashboard.Router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :fetch_live_flash
    plug :put_root_layout, {ChromoidWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :fetch_current_user
  end

  scope "/", ChromoidWeb do
    pipe_through :browser
    get "/", PageController, :index
    live "/test", TestLive, :index
    get "/discord/oauth", DiscordOauthController, :oauth
  end

  ## Authentication routes

  scope "/", ChromoidWeb do
    pipe_through [:browser, :redirect_if_user_is_authenticated]

    get "/users/register", UserRegistrationController, :new
    post "/users/register", UserRegistrationController, :create
  end

  scope "/", ChromoidWeb do
    pipe_through [:browser, :require_authenticated_user]
    get "/logout", DiscordOauthController, :logout
    live "/devices", DeviceLive, :index
    live "/devices/:id", DeviceLive, :show
    live "/devices/:id/nfc", DeviceNFCLive, :show
    live "/devices/:device_id/nfc/:nfc_id/webhooks", NFCWebhookLive, :show
    live "/devices/:device_id/nfc/:nfc_id/actions", NFCActionLive, :show
    live "/recipes", RecipeLive, :index
    get "/devices/:id/stream", DeviceController, :stream
    get "/devices/:id/live.mjpg", DeviceController, :live
    # live "/recipes/:id", RecipeLive, :show
  end

  scope "/", ChromoidWeb do
    pipe_through [:browser, :require_authenticated_user, :require_admin_user]
    live_dashboard "/admin/dashboard", metrics: ChromoidWeb.Telemetry
    live "/scripts", ScriptLive, :index

    resources "/scripts", ScriptController, only: [:edit] do
      put "/save", ScriptController, :save
      put "/update", ScriptController, :update
    end

    get "/console", ConsoleController, :index
  end

  scope "/", ChromoidWeb do
    pipe_through [:browser]

    get "/users/confirm", UserConfirmationController, :new
    post "/users/confirm", UserConfirmationController, :create
    get "/users/confirm/:token", UserConfirmationController, :confirm
  end
end

chromoid_web/lib/speediview_ui/layout.ex
defmodule SpeediViewUI.Layout do
  @moduledoc """
  Saves layouts to disk for next startup
  """

  @doc "Save the layout to disk"
  def save(layout) do
    # remote_reload(layout)
    File.write!(layout_file(), :erlang.term_to_binary(layout))
  end

  @doc "Lazily load the layout from disk"
  def load() do
    case File.read(layout_file()) do
      {:ok, bin} -> :erlang.binary_to_term(bin)
      _ -> %{}
    end
  end

  defp layout_file do
    Application.get_env(:speediview, __MODULE__, [])[:layout_file] || "layout.etf"
  end

  # if Mix.Project.config()[:target] == "host" do
  #   defp remote_reload(layout) do
  #     Node.stop()
  #     config = Mix.Project.config()
  #     cookie = config[:releases][config[:app]][:cookie]
  #     node_name = :"dash@sv-fd86.local"
  #     IO.puts "reloading layout on #{node_name}"
  #     {:ok, _} = Node.start(:"reload@0.0.0.0")
  #     Node.set_cookie(String.to_atom(cookie))
  #     true = Node.connect(node_name)
  #     :rpc.call(node_name, __MODULE__, :save, [layout])
  #     :rpc.call(node_name, Application, :stop, [:speediview])
  #     :rpc.call(node_name, Application, :start, [:speediview])
  #   end
  # else
  #   defp remote_reload(_), do: :ok
  # end
end

chromoid_web/lib/chromoid_web/views/layout_view.ex
defmodule ChromoidWeb.LayoutView do
  use ChromoidWeb, :view

  def active?(conn, "/") do
    conn.private[:phoenix_controller] == ChromoidWeb.PageController
  end

  def active?(conn, "/devices" <> _) do
    match?({ChromoidWeb.DeviceLive, _}, conn.private[:phoenix_live_view])
  end

  def active?(conn, "/scripts" <> _) do
    match?({ChromoidWeb.ScriptLive, _}, conn.private[:phoenix_live_view]) ||
      conn.private[:phoenix_controller] == ChromoidWeb.ScriptController
  end

  def active?(_conn, _link) do
    false
  end
end

chromoid_web/lib/chromoid_web/templates/layout/_user_menu.html.eex
    <nav class="flex items-center justify-between flex-wrap bg-teal-500 p-6" x-data="{ open: false }">
      <div class="flex items-center flex-shrink-0 text-white mr-6">
        <svg class="fill-current h-8 w-8 mr-2" width="54" height="54" viewBox="0 0 54 54" xmlns="http://www.w3.org/2000/svg"><path d="M13.5 22.1c1.8-7.2 6.3-10.8 13.5-10.8 10.8 0 12.15 8.1 17.55 9.45 3.6.9 6.75-.45 9.45-4.05-1.8 7.2-6.3 10.8-13.5 10.8-10.8 0-12.15-8.1-17.55-9.45-3.6-.9-6.75.45-9.45 4.05zM0 38.3c1.8-7.2 6.3-10.8 13.5-10.8 10.8 0 12.15 8.1 17.55 9.45 3.6.9 6.75-.45 9.45-4.05-1.8 7.2-6.3 10.8-13.5 10.8-10.8 0-12.15-8.1-17.55-9.45-3.6-.9-6.75.45-9.45 4.05z"/></svg>
        <span class="font-semibold text-xl tracking-tight">Chromoid</span>
      </div>

      <div class="block lg:hidden">
        <button class="flex items-center px-3 py-2 border rounded text-teal-200 border-teal-400 hover:text-white hover:border-white" @click="open=true">
          <svg class="fill-current h-3 w-3" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><title>Menu</title><path d="M0 3h20v2H0V3zm0 6h20v2H0V9zm0 6h20v2H0v-2z"/></svg>
        </button>
      </div>

      <div class="w-full block flex-grow lg:flex lg:items-center lg:w-auto" x-show="open" @click.away="open=false">
        <div class="text-sm lg:flex-grow">
          <%= if @current_user do %>
            <a href="<%= Routes.device_path(@conn, :index) %>" class="block mt-4 lg:inline-block lg:mt-0 text-teal-200 hover:text-white mr-4">
              Devices
            </a>
          <% end %>
        </div>

        <div>
          <%= if @current_user do %>
            <%= link "Log Out", to: Routes.discord_oauth_path(@conn, :logout), class: "inline-block text-sm px-4 py-2 leading-none border rounded text-white border-white hover:border-transparent hover:text-teal-500 hover:bg-white mt-4 lg:mt-0" %>
          <% else %>
            <%= link "Authorize with Discord", to: ChromoidDiscord.OAuth.authorization_url, class: "inline-block text-sm px-4 py-2 leading-none border rounded text-white border-white hover:border-transparent hover:text-teal-500 hover:bg-white mt-4 lg:mt-0" %>
          <% end %>
        </div>
      </div>
    </nav>

chromoid_web/lib/chromoid_web/templates/layout/app.html.eex
<% error_flash = get_flash(@conn, :error) %>
<% info_flash = get_flash(@conn, :error) %>

<%= if error_flash do %>
  <div class="alert alert-danger m-1 bg-red-200 border border-red-400 text-red-700 px-4 py-3 rounded relative" role="alert">
    <p class="block sm:inline"><%= error_flash %></p>
  </div>
<% end %>

<%= if info_flash do %>
  <div class="alert alert-danger m-1 bg-blue-200 border border-blue-400 text-blue-900 px-4 py-3 rounded relative" role="alert">
    <p class="block sm:inline"><%= info_flash %></p>
  </div>
<% end %>

<%= @inner_content %>

chromoid_web/lib/chromoid_web/templates/layout/live.html.leex
<% flash_info = live_flash(@flash, :info) %>
<% flash_error = live_flash(@flash, :error) %>

<%= if flash_error do %>
  <div class="alert alert-danger m-1 bg-red-200 border border-red-400 text-red-700 px-4 py-3 rounded relative" role="alert">
    <p class="block sm:inline" phx-click="lv:clear-flash" phx-value-key="info"><%= flash_error %></p>
  </div>
<% end %>

<%= if flash_info do %>
  <div class="alert alert-danger m-1 bg-blue-200 border border-blue-400 text-blue-900 px-4 py-3 rounded relative" role="alert">
    <p class="block sm:inline" phx-click="lv:clear-flash" phx-value-key="error" > <%= flash_info %></p>
  </div>
<% end %>

<%= @inner_content %>

chromoid_web/lib/chromoid_web/templates/layout/root.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Chromoid Dashboard</title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/editor.css") %>"/>
    <%= csrf_meta_tag() %>
    <script defer type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </head>
  <body class="bg-gray-800">

  <nav
      class="flex items-center justify-between flex-wrap p-6 bg-indigo-500"
      x-data="{ isOpen: false }"
      @keydown.escape="isOpen = false"
      :class="{ 'shadow-lg bg-indigo-500' : isOpen , 'bg-indigo-500' : !isOpen}"
    >
      <!--Logo etc-->
      <div class="flex items-center flex-shrink-0 text-white mr-6">
        <a
          class="text-white no-underline hover:text-white hover:no-underline"
          href="/"
        >
          <span class="text-2xl pl-2">Chromoid</span>
        </a>
        <%= unless @current_user do %>
          <%= link "Login with Discord",
            to: ChromoidDiscord.OAuth.authorization_url(),
            class: "block text-sm mx-1 px-1 py-2 leading-none border rounded text-white border-white hover:border-transparent hover:text-indigo-500 hover:bg-white lg:mt-0"
          %>
        <% end %>
      </div>


      <!--Toggle button (hidden on large screens)-->
      <button
        @click="isOpen = !isOpen"
        type="button"
        class="block lg:hidden px-2 text-gray-500 hover:text-white focus:outline-none focus:text-white"
        :class="{ 'transition transform-180': isOpen }"
      >
        <svg
          class="h-6 w-6 fill-current"
          xmlns="http://www.w3.org/2000/svg"
          viewBox="0 0 24 24"
        >
          <path
            x-show="isOpen"
            fill-rule="evenodd"
            clip-rule="evenodd"
            d="M18.278 16.864a1 1 0 0 1-1.414 1.414l-4.829-4.828-4.828 4.828a1 1 0 0 1-1.414-1.414l4.828-4.829-4.828-4.828a1 1 0 0 1 1.414-1.414l4.829 4.828 4.828-4.828a1 1 0 1 1 1.414 1.414l-4.828 4.829 4.828 4.828z"
          />
          <path
            x-show="!isOpen"
            fill-rule="evenodd"
            d="M4 5h16a1 1 0 0 1 0 2H4a1 1 0 1 1 0-2zm0 6h16a1 1 0 0 1 0 2H4a1 1 0 0 1 0-2zm0 6h16a1 1 0 0 1 0 2H4a1 1 0 0 1 0-2z"
          />
        </svg>
      </button>

      <!--Menu-->
      <div
        class="w-full flex-grow lg:flex lg:items-center lg:w-auto"
        :class="{ 'block shadow-3xl': isOpen, 'hidden': !isOpen }"
        @click.away="isOpen = false"
        x-show.transition="true"
      >
        <ul
          class="pt-6 lg:pt-0 list-reset lg:flex justify-end flex-1 items-center"
        >
          <li class="mr-3">
            <a
              class="<%= if active?(@conn, Routes.page_path(@conn, :index)), do: "inline-block py-2 px-4 text-white no-underline", else: "inline-block text-gray-500 no-underline hover:text-gray-200 hover:text-underline py-2 px-4" %>"
              href="<%= Routes.page_path(@conn, :index) %>"
              @click="isOpen = false"
              >Dashboard
            </a>
          </li>
          <%= if @current_user do %>

            <li class="mr-3">
              <a
                class="<%= if active?(@conn, Routes.device_path(@conn, :index)), do: "inline-block py-2 px-4 text-white no-underline", else: "inline-block text-gray-500 no-underline hover:text-gray-200 hover:text-underline py-2 px-4" %>"
                href="<%= Routes.device_path(@conn, :index) %>"
                @click="isOpen = false"
                >Devices
              </a>
            </li>

            <%= if @current_user.admin do %>
              <li class="mr-3">
                <a
                  class="<%= if active?(@conn, Routes.script_path(@conn, :index)), do: "inline-block py-2 px-4 text-white no-underline", else: "inline-block text-gray-500 no-underline hover:text-gray-200 hover:text-underline py-2 px-4" %>"
                  href="<%= Routes.script_path(@conn, :index) %>"
                  @click="isOpen = false"
                  >Scripts
                </a>
              </li>

              <li class="mr-3">
                <a
                  class="<%= if active?(@conn, Routes.live_dashboard_path(@conn, :home)), do: "inline-block py-2 px-4 text-white no-underline", else: "inline-block text-gray-500 no-underline hover:text-gray-200 hover:text-underline py-2 px-4" %>"
                  href="<%= Routes.live_dashboard_path(@conn, :home) %>"
                  @click="isOpen = false"
                  >Admin Dashboard
                </a>
              </li>
            <% end %>
          <% end %>

        </ul>
      </div>
    </nav>

    <%= @inner_content %>
  </body>
</html>